from aiogram import Router, F
from aiogram.types import CallbackQuery, Message
from keyboards import back_to_menu_kb

router = Router()

HELP_TEXT = (
    "⚠️ <b>Help Center — Promote Auto by @berryrcr</b>\n"
    "\n"
    "━━━━━━━━━━━━━━━\n"
    "\n"
    "⚡️ <b>Cara Guna (ikut flow latest)</b>\n"
    "\n"
    "1️⃣ <b>Topup syiling</b>\n"
    "🛒 Shop Zone → 💳 Reload Syiling💸\n"
    "\n"
    "2️⃣ <b>Buy Userbot</b>\n"
    "🛒 Shop Zone → 🛍 Buy Userbot\n"
    "\n"
    "• 300 Syiling\n"
    "• Lifetime access\n"
    "• 1 account only\n"
    "\n"
    "3️⃣ <b>Activate Plan</b>\n"
    "🛠️ Setup Month &amp; Plan\n"
    "\n"
    "Pilih:\n"
    "💎 PLUS atau 🚀 PRO\n"
    "\n"
    "4️⃣ <b>Connect Telegram Account</b>\n"
    "📚 Create Userbot\n"
    "\n"
    "Masukkan nombor Telegram &amp; OTP/login code 🔐\n"
    "\n"
    "5️⃣ <b>Setup Group</b>\n"
    "⚙️ Control Panel → 👥 Manage Group\n"
    "\n"
    "Pilih group/channel korang sendiri untuk promote.\n"
    "\n"
    "6️⃣ <b>Setup Promote Message</b>\n"
    "⚙️ Control Panel → 📝 Edit Message\n"
    "\n"
    "7️⃣ <b>Setup Delay Timer</b>\n"
    "⚙️ Control Panel → ⏱️ Delay Timer\n"
    "\n"
    "Recommended:\n"
    "30–60 minit untuk lebih selamat 🛡️\n"
    "\n"
    "8️⃣ <b>Start Promote</b>\n"
    "⚙️ Control Panel → 🚀 Start Promote\n"
    "\n"
    "Done ✅\n"
    "Bot akan auto running ikut timer &amp; schedule korang 💨\n"
    "\n"
    "━━━━━━━━━━━━━━━\n"
    "\n"
    "🧩 <b>Userbot vs Subscription Plan</b>\n"
    "\n"
    "🧩 <b>Userbot</b>\n"
    "= Lifetime access untuk connect Telegram account\n"
    "\n"
    "💎 <b>Subscription Plan</b>\n"
    "= Unlock feature &amp; auto promote system\n"
    "\n"
    "Userbot dan plan ialah dua benda berbeza.\n"
    "\n"
    "━━━━━━━━━━━━━━━\n"
    "\n"
    "💎 <b>PLAN PLUS</b>\n"
    "\n"
    "Perfect untuk normal daily promote 🔥\n"
    "\n"
    "• Max 3 saved promote message\n"
    "• Basic auto promote system\n"
    "• Standard safe mode protection\n"
    "• Smooth untuk casual seller\n"
    "• Easy &amp; simple setup\n"
    "\n"
    "━━━━━━━━━━━━━━━\n"
    "\n"
    "🚀 <b>PLAN PRO</b>\n"
    "\n"
    "Built untuk serious seller &amp; heavy promote ⚡\n"
    "\n"
    "• Unlimited rotate message\n"
    "• Smarter auto promote system\n"
    "• Better anti-flood &amp; safe mode\n"
    "• More stable untuk banyak group\n"
    "• Faster &amp; cleaner promote performance\n"
    "• Future premium feature unlock 🔥\n"
    "\n"
    "━━━━━━━━━━━━━━━\n"
    "\n"
    "🛡️ <b>Auto Safe Mode</b>\n"
    "\n"
    "Sistem akan auto protect account korang jika detect:\n"
    "• FloodWait\n"
    "• PeerFlood\n"
    "• Too many failed sends\n"
    "\n"
    "Bot akan auto:\n"
    "• naikkan delay sementara\n"
    "• protect account\n"
    "• restore balik setting asal bila stable ✅\n"
    "\n"
    "━━━━━━━━━━━━━━━\n"
    "\n"
    "⚠️ <b>Heads Up</b>\n"
    "\n"
    "• Bot hanya send ke group/channel yang korang pilih sendiri\n"
    "• Bot TAK auto join atau scrape random group\n"
    "• Simpan ID Userbot korang untuk backup access\n"
    "• Elakkan delay terlalu rendah untuk kurangkan risiko limit\n"
    "\n"
    "━━━━━━━━━━━━━━━"
)


@router.message(F.text == "⚠️ Help Center")
async def msg_help(message: Message):
    await message.answer(HELP_TEXT, parse_mode="HTML", reply_markup=back_to_menu_kb())


@router.callback_query(F.data == "help")
async def cb_help(callback: CallbackQuery):
    await callback.message.edit_text(HELP_TEXT, parse_mode="HTML", reply_markup=back_to_menu_kb())
    await callback.answer()
